apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
    name: vti-es-ivm
  name: vti-es-ivm
---
apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_NAME: Laravel
  APP_URL: http://localhost:8000
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: pgsql
  DB_DATABASE: vti_ivm
  DB_HOST: postgres
  DB_PORT: "5432"
  DOMAIN_ADMIN: admin.localhost
  DOMAIN_CMS: cms.localhost
  DOMAIN_REGISTER: register.localhost
  FILESYSTEM_DRIVER: local
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  QUEUE_CONNECTION: sync
  REDIS_HOST: 10.0.138.13
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
  name: vti-es-ivm-config
  namespace: vti-es-ivm
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
  name: vti-es-ivm-secret
  namespace: vti-es-ivm
stringData:
  APP_KEY: base64:LANHDiqULd0q/rHCUiX6rvb+3EmSpSXgtdt298nO/bk=
  DB_PASSWORD: IVm@2020
  DB_USERNAME: vti_dev
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: Laravel
  MAIL_HOST: smtp.mailtrap.io
  MAIL_MAILER: log
  MAIL_PASSWORD: 056b0eb5cbc6b3
  MAIL_PORT: "587"
  MAIL_USERNAME: 112b82ad3aad66
  REDIS_PASSWORD: redis
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
  name: vti-es-ivm
  namespace: vti-es-ivm
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vti-es-ivm
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vti-es-ivm
    app.kubernetes.io/part-of: vti-es-ivm
  name: vti-es-ivm
  namespace: vti-es-ivm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vti-es-ivm
      app.kubernetes.io/name: vti-es-ivm
      app.kubernetes.io/part-of: vti-es-ivm
  template:
    metadata:
      labels:
        app: vti-es-ivm
        app.kubernetes.io/name: vti-es-ivm
        app.kubernetes.io/part-of: vti-es-ivm
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: vti-es-ivm-config
        - secretRef:
            name: vti-es-ivm-secret
        image: saas:latest
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        name: vti-es-ivm
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - configMap:
          name: vti-es-ivm-php-config
        name: php-config
