version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saas:latest
    container_name: saas
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini