apiVersion: v1
kind: Service
metadata:
  name: vti-es-ivm
  namespace: vti-es-ivm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: vti-es-ivm 