version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VIEW_COMPILED_PATH=/var/www/storage
    working_dir: /var/www
    volumes:
      - ..:/var/www
    ports:
      - "8000:8000"
    networks:
      - vti-es-ivm
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - dashboard
    ports:
      - "8080:80"
    networks:
      - vti-es-ivm
    volumes:
      - ..:/var/www
      - ../nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vti_ivm
      POSTGRES_USER: vti_dev
      POSTGRES_PASSWORD: IVm@2020
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vti-es-ivm

networks:
  vti-es-ivm:
    external: true
    name: vti-es-ivm

volumes:
  mysql_data:
  pgdata: